### ISSUE TITLE
Initial code review

### ISSUE THREAD

**Issue by joeyklee** [joeyklee/urbanco2#1]
Just an initial code review to make sure what I've done isn't completely going to block us later. This is my first time developing from scratch, so having another pair of eyes would be superb :)

**Comment by blahah** [comment]
Checking it out now

**Comment by blahah** [comment]
Had a scan through and cloned/ran the code. Looking really nice! I made a few minor changes in this PR: https://github.com/joeyklee/urbanco2/pull/5. All just small things to help people like me use/read the code.

Small points:
- There's a bunch of stuff commented out, but I assume that will get cleaned as the project matures
- Maybe add a `.editorconfig` and setup your editor to use it? http://editorconfig.org. There's a lot of inconsistent spacing (assume from copy/paste).

**Comment by joeyklee** [comment]
Thanks for the feedback - the setup stuff was crucial! 

Re small points:
1. Yep - all the commented stuff will eventually make its way out. Sometimes it's handy for my reference. Pardon the gobblyglop 
2. Nice suggestion - just plopped one in the root folder :)
