### ISSUE TITLE
full screen button on explore page is wonky - css conflicts I think

### ISSUE THREAD

**Issue by joeyklee** [joeyklee/urbanco2#15]
should look like this: https://www.mapbox.com/mapbox.js/example/v1.0.0/leaflet-fullscreen/

but seems there's issues with the size of the button. not crucial task at the moment, but good not to forget it!

**Comment by briantjacobs** [comment]
```
<link href='https://api.mapbox.com/mapbox.js/plugins/leaflet-fullscreen/v1.0.1/leaflet.fullscreen.css' rel='stylesheet' />
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.7/leaflet.css">
```

^^^ swap the order of these

**Comment by joeyklee** [comment]
Boom! that was a silly mistake. thanks for that!!
