### ISSUE TITLE
Deploying test to heroku or digital ocean or openshift

### ISSUE THREAD

**Issue by joeyklee** [joeyklee/urbanco2#22]
I could use a tip on how to deploy nodejs w/ mongodb to a hosting service. It seems straightforward to push nodejs, but mongo requires some extra tinkering. I'll play a bit more, but ultimately I would need some help with best practices :)

**Comment by blahah** [comment]
Easiest way to do this for digitalocean is to use the MEAN premade image: https://www.digitalocean.com/community/tutorials/how-to-use-the-mean-one-click-install-image

**Comment by joeyklee** [comment]
Nice - will check it out and test. Thanks!

**Comment by abbycabs** [comment]
In case you want to go the heroku route, I use the mongolab add-on. Free up  to 5G.
