### ISSUE TITLE
get URL domain

### ISSUE THREAD

**Issue by joeyklee** [joeyklee/urbanco2#26]

**Comment by joeyklee** [comment]
[http://urbanco2.jk-lee.com/](http://urbanco2.jk-lee.com/)
added CNAME to godaddy account:

![screen shot 2016-02-17 at 11 02 09 am](https://cloud.githubusercontent.com/assets/3622055/13121139/f197ebfe-d565-11e5-9904-2a975839d898.png)

and then added it to heroku 

![screen shot 2016-02-17 at 11 02 49 am](https://cloud.githubusercontent.com/assets/3622055/13121156/059287a4-d566-11e5-90db-3f826f69f696.png)

**Comment by blahah** [comment]
Hells yeah!
