### ISSUE TITLE
UI/UX - scroll from page to page?

### ISSUE THREAD

**Issue by joeyklee** [joeyklee/urbanco2#3]
RIght now there's a button at the end of the scoll-splanation, but it would be great to be able to scroll from page to page... or would it? maybe scrolling to the next page is distracting if the user overscrolls?

**Comment by blahah** [comment]
There's some research on this... _goes to look for it_

**Comment by blahah** [comment]
[Found some](https://scholar.google.co.uk/scholar?as_vis=1&q=scrolling+pagination)... it's essentially all inconclusive with regards to which is better.

Pagination gives a sense of control and makes it a bit easier to find specific bits of information, but requires more interaction and interrupts the flow of information.

Scrolling requires less mental distraction to follow a narrative and allows continuous information retrieval but makes it harder to find a specific piece of information, and can be more resource intensive (but these days, browsers can handle it).

**Comment by joeyklee** [comment]
Thanks @Blahah. For now, let's stick to the button and we can once the next page is up. I will leave #3 open.

**Comment by blahah** [comment]
now that I've seen how you do it I think it's perfect as it is: scrolling within a chapter, clicking to change chapter. Seems like a great balance.

**Comment by joeyklee** [comment]
@Blahah thanks for looking into it. Nice. We can reopen #3 if we feel the interaction feels wonky. Otherwise, onward!
